### ISSUE TITLE
Validation allows blank selection for required field

### ISSUE THREAD

**Issue by dtamai** [getninjas/jason#61]
**Description**

A required select field with nested values allows a blank selection when its reference changes, but the last selection was valid.

**Steps to reproduce**

I created a simple form with two fields, a select field and a dependent select field, and recorded the issue:

![Peek 2019-07-03 14-25](https://user-images.githubusercontent.com/1813743/60612886-2570fa00-9da0-11e9-94df-70348cfe3555.gif)

1. select a valid option for the first field
2. select a valid option for the second field
3. change the selection for the first field - now the second doesn't have anything selected
4. submit bypassing the validation

**Comment by iondrimba** [comment]
Thanks for the awesome GIF! 🙏 @dtamai
